
import "./globals.css";
import Header from "./header/header"
import Footer from "./footer/footer";

import localFont from "next/font/local";
const myFont = localFont({
  src: "./font/InterTight-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={myFont.className}>
        <div className="w-[100%]">

        <Header/>
        {children}
        <Footer/>

        </div>
      </body>
    </html>
  );
}



